{% set name = "pyboat" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86c2dde710abd28619f627bf34646b16fe57d6f020fcf76e6979f9414bdcc5c2
build:
  number: 0
  noarch: python
  entry_points:
    - pyboat = pyboat:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2.3
  run:
    - matplotlib >=3.1
    - numpy >=1.18
    - pandas >=0.25
    - pyqt >=5.9
    - python >=3.6
    - scipy >=1.4
    - flit-core >=2.3

test:
  source_files:
    - scripting_demo.py
  imports:
    - pyboat

app:
  entry: pyBOAT
  summary: pyBOAT GUI - Interactive wavelet analysis for biological data. Provides phase, period and amplitude extraction of non-stationary oscillatory signals.'
  type: desk
  icon: logo_96x96.png

about:
  home: https://github.com/tensionhead/pyboat
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: pyBOAT - A Biological Oscillations Analysis Toolkit
  description: "Interactive time-frequency analysis for biological data\nusing wavelets. Features optimal sinc filter for\ndetrending and provides phase, period and amplitude\nextraction of non-stationary oscillatory signals."
  dev_url: https://github.com/tensionhead/pyboat

extra:
  recipe-maintainers:
    - tensionhead
